[package]
name = "blog_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.11"
scraper = "0.13"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1"
